services:
  bot:
    build: .
    container_name: telega_bot
    restart: unless-stopped
    environment:
      - TOKEN=  # Замените на ваш токен
    volumes:
      - .:/app
    networks:
      - bot_network

networks:
  bot_network:
    driver: bridge
