# Generated by Django 5.1.5 on 2025-02-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elemetsgame',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
