# Generated by Django 5.1.5 on 2025-02-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_elemetsgame_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='elemetsgame',
            name='true_rez',
            field=models.IntegerField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
