# Generated by Django 5.1.5 on 2025-02-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_elemetsgame_true_rez'),
    ]

    operations = [
        migrations.AddField(
            model_name='elemetsgame',
            name='itog_txt',
            field=models.TextField(blank=True),
        ),
    ]
